// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Videogames.Models;

namespace Videogames.Migrations
{
    [DbContext(typeof(MyContext))]
    partial class MyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Videogames.Models.Videogame", b =>
                {
                    b.Property<int>("VideogameId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("createdAt");

                    b.Property<string>("genre")
                        .IsRequired();

                    b.Property<string>("studio")
                        .IsRequired();

                    b.Property<string>("title")
                        .IsRequired();

                    b.Property<DateTime>("updatedAt");

                    b.Property<int>("year");

                    b.HasKey("VideogameId");

                    b.ToTable("Games");
                });
#pragma warning restore 612, 618
        }
    }
}
